baseURL = "https://johndoe.dev"
languageCode = 'en-us'
title = 'John Doe'
theme = 'doe-minimalistic'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "John Doe"
location = "Anytown, USA"
description = "AI Developer. ML Engineer. I finetune models, build scalable pipelines and automate workflows."
profile_image = "/images/profile.jpg"
discord = "johndoe123"
github = "https://github.com/johndoe123"
github_username = "johndoe123"
email = "johndoe@example.com"
twitter = "https://www.twitter.com/johndoe123"
twitter_username = "johndoe123"
medium = "https://www.medium.com/@johndoe123"
linkedin = "https://www.linkedin.com/in/johndoe123"
linkedin_username = "johndoe123"
instagram = "https://instagram.com/johndoe123"
leetcode = "https://leetcode.com/johndoe123"
leetcode_username = "johndoe123"
monkeytype = "https://monkeytype.com/profile/johndoe123"
monkeytype_username = "johndoe123"
kaggle = "https://www.kaggle.com/johndoe123"
kaggle_username = "johndoe123"

[[params.honors]]
institution = "Generic College"
title = "Academic Topper"
date = "March 2023"

[[params.honors]]
institution = "Valley High Academy"
title = "Outstanding Achievement in STEM"
date = "May 2018"

[[params.certifications]]
title = "Azure AI Engineering Specialist"
date = "Dec 2024"
url = "https://example.com/cert-azure"

[[params.certifications]]
title = "Google Cloud ML Professional"
date = "March 2024" 
url = "https://example.com/cert-gcp"

[[params.experience]]
company = "DataFlow Systems"
role = "AI Research Intern"
period = "May 2023 - Aug 2023"
logo = "/images/company/dataflow.png"
description = "Built computer vision models for retail analytics and customer behavior prediction."
responsibilities = [
    "Developed object detection models using YOLOv8 for in-store customer tracking",
    "Implemented real-time analytics pipeline reducing processing latency by 35%",
    "Created interactive dashboards using Grafana and Tableau for business insights",
    "Optimized model inference on edge devices improving throughput by 40%"
]

[[params.experience]]
company = "CloudMatrix"
role = "Data Science Intern" 
period = "Jan 2022 - April 2022"
logo = "/images/company/cloudmatrix.png"
description = "Developed recommendation systems and predictive models for e-commerce platform."
responsibilities = [
    "Built collaborative filtering recommendation engine using PyTorch",
    "Implemented A/B testing framework for model evaluation",
    "Optimized data preprocessing pipeline reducing training time by 60%",
    "Created automated reporting system using Python and PowerBI"
]

[[params.experience]]
company = "WebTech Solutions"
role = "Analytics Intern"
period = "June 2020 - Aug 2020"
logo = "/images/company/webtech.png"
description = "Analyzed web traffic patterns and user behavior for SaaS products."
responsibilities = [
    "Implemented tracking systems using Google Analytics and Mixpanel",
    "Created user segmentation models to identify high-value customers",
    "Developed automated reporting system for key business metrics"
]

[[params.experience]]
    company = "GitLab"
    role = "Open Source Contributor"
    period = "Jan 2024 - Present"
    description = "Regular contributor to open source ML and data science projects"
    github_username = "johndoe123"

[[params.projects]]
    title = "Smart City Traffic Management"
    description = "An AI-powered system using computer vision and reinforcement learning to optimize traffic flow in urban areas. Features real-time monitoring, predictive analytics, and adaptive signal control."
    tech = "Python, TensorFlow, OpenCV, Ray, Redis"
    image = "/images/projects/traffic_ai.png"
    link = "https://github.com/johndoe123/smart-traffic"

[[params.projects]]
    title = "Echo - Multilingual Voice Assistant"
    description = "A voice-enabled AI assistant supporting 12 languages with real-time translation and natural conversation capabilities. Built during HackTech 2024."
    tech = "Python, FastAPI, Whisper, Azure Speech Services, MongoDB"
    image = "/images/projects/echo.png"
    link = "https://devpost.com/software/echo-assistant"

[[params.projects]]
    title = "CodePilot - Developer Tool"
    description = "VS Code extension that provides intelligent code suggestions and documentation using local LLMs."
    tech = "TypeScript, Node.js, Ollama, SQLite"
    image = "/images/projects/codepilot.png"
    link = "https://github.com/johndoe123/codepilot"

[[params.projects]]
    title = "Neural Style Transfer"
    description = "Implementation of artistic style transfer using deep neural networks and custom loss functions."
    tech = "PyTorch, CUDA, Flask, Docker"
    image = "/images/projects/style-transfer.png"
    link = "https://github.com/johndoe123/neural-artist"

[[params.projects]]
    title = "HealthBot - Healthcare AI"
    description = "Medical chatbot using RAG and custom medical knowledge base for preliminary health assessments."
    tech = "Python, LangChain, Pinecone, FastAPI"
    image = "/images/projects/healthbot.png"
    link = "https://github.com/johndoe123/healthbot"

[[params.projects]]
    title = "Quantum Computing Simulator"
    description = "Educational tool for simulating basic quantum circuits and algorithms."
    tech = "Python, Qiskit, NumPy, Streamlit"
    image = "/images/projects/quantum-sim.jpg"
    link = "https://github.com/johndoe123/quantum-edu"

[[params.projects]]
    title = "SmartMail - Email Automation"
    description = "Email classification and response automation system using transformer models."
    tech = "Python, Hugging Face, FastAPI, RabbitMQ"
    image = "/images/projects/smartmail.png"
    link = "https://github.com/johndoe123/smartmail"

[[params.projects]]
    title = "Video Enhancement AI"
    description = "Real-time video upscaling and enhancement using deep learning models."
    tech = "Python, TensorRT, CUDA, FFmpeg"
    image = "/images/projects/video_ai.png"
    link = "https://github.com/johndoe123/video-enhance"

[[params.projects]]
    title = "Market Sentiment Analyzer"
    description = "Financial market sentiment analysis using NLP and social media data."
    tech = "Python, BERT, FastAPI, Redis, TA-Lib"
    image = "/images/projects/market_sentiment.png"
    link = "https://github.com/johndoe123/market-pulse"

[[params.projects]]
    title = "Urban Explorer - Mobile App"
    description = "Location-based recommendation system for discovering local events and places."
    tech = "React Native, Node.js, MongoDB, Google Maps API"
    image = "/images/projects/urban_explorer.jpg"
    link = "https://github.com/johndoe123/urban-explorer"

[[params.blogs]]
    title = "Building Scalable AI Systems with Ray"
    date = "2025-03-15"
    summary = "A deep dive into distributed computing for AI workloads using Ray framework."
    tags = ["Distributed Systems", "Ray", "AI Infrastructure"]
    content = """
    Learn how to scale your AI applications from laptop to cluster using Ray's distributed computing framework...
    """
    link = "https://medium.com/@johndoe123/building-scalable-ai-systems-with-ray-8f92a45b12d0"

[[params.blogs]]
    title = "The Future of Edge AI"
    date = "2025-02-28"
    summary = "Exploring the latest developments in edge computing for AI applications."
    tags = ["Edge AI", "IoT", "TinyML"]
    content = """
    Edge AI is revolutionizing how we deploy and run AI models in resource-constrained environments...
    """
    link = "https://medium.com/@johndoe123/future-of-edge-ai-d7e9f4a2b1c3"

[[params.blogs]]
    title = "Quantum Machine Learning: A Practical Guide"
    date = "2025-02-10"
    summary = "Introduction to quantum computing concepts for machine learning practitioners."
    tags = ["Quantum Computing", "ML", "Tutorial"]
    content = """
    Understanding how quantum computing principles can enhance machine learning algorithms...
    """
    link = "https://medium.com/@johndoe123/quantum-ml-guide-7b3f9c2a4d5e"

[[params.blogs]]
    title = "Optimizing Large Language Models"
    date = "2025-01-20"
    summary = "Techniques for efficient training and deployment of large language models."
    tags = ["LLM", "Optimization", "MLOps"]
    content = """
    Practical strategies for reducing training costs and improving inference speed in LLMs...
    """
    link = "https://medium.com/@johndoe123/optimizing-llms-9a8b7c6d5e4f"

[[params.blogs]]
    title = "Neural Architecture Search: A Comprehensive Guide"
    date = "2024-12-15"
    summary = "Understanding automated neural network design using NAS techniques."
    tags = ["Deep Learning", "AutoML", "NAS"]
    content = """
    Exploring different approaches to automated neural network architecture design...
    """
    link = "https://medium.com/@johndoe123/neural-architecture-search-guide-3f7b9c1a2d4e"

[[params.blogs]]
    title = "Federated Learning in Practice"
    date = "2024-11-20"
    summary = "Real-world implementation of privacy-preserving machine learning."
    tags = ["Federated Learning", "Privacy", "ML"]
    content = """
    How to implement federated learning for privacy-sensitive applications...
    """
    link = "https://medium.com/@johndoe123/federated-learning-practice-5e6f7c8d9a3b"

[[params.blogs]]
    title = "Graph Neural Networks for Recommendation Systems"
    date = "2024-10-25"
    summary = "Leveraging graph-based deep learning for better recommendations."
    tags = ["GNN", "RecSys", "Deep Learning"]
    content = """
    Building modern recommendation systems using graph neural networks...
    """
    link = "https://medium.com/@johndoe123/gnn-recommendation-systems-2c4b8e7f9d6a"

[[params.blogs]]
    title = "MLOps Best Practices"
    date = "2024-09-30"
    summary = "Essential practices for production machine learning systems."
    tags = ["MLOps", "DevOps", "Production ML"]
    content = """
    Key principles and practices for maintaining ML systems in production...
    """
    link = "https://medium.com/@johndoe123/mlops-best-practices-4a5b9c8d7e6f"

[[params.voluntary]]
role = "Tech Mentor"
organization = "Code for Change"
period = "2020 - Present"
description = "Mentoring underprivileged students in programming and AI, organizing coding workshops, and contributing to open-source educational projects. Led initiatives to bridge the digital divide in local communities."

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5